[Path]
H3FileName=

;FntMode=1为字体竖放(中文版字体取模方式)，FntMode=2为字体横放(用任意汉字生成的字体取模方式)

[Font]
Fnt10=hzk10
Fnt10Mode=2

Fnt12=hzk12
Fnt12Mode=2

Fnt24=hzk24
Fnt24Mode=2


;FontType=1表示GB，FontType=2表示GBK
FontType=1

